#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d  󰈹  

bspc config border_width         0
bspc config window_gap           4

bspc config normal_border_color	    "#1e1e2e"
bspc config active_border_color	    "#f0c674"
bspc config focused_border_color	"#cdd6f4"
bspc config presel_feedback_color	"#b48ead"
bspc config urgent_border_color 	"#ff4040"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# autostart applications

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
